// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/journals/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/journals/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/journals/[id].put').default>>>>
    }
    '/api/journals/:id/todos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/journals/[id]/todos.get').default>>>>
    }
    '/api/journals': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/journals/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/journals/index.post').default>>>>
    }
    '/api/todos/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/[id].put').default>>>>
    }
    '/api/todos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}