// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/22/2026, 8:56:28 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/marclange/Sites/node_vue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marclange/Sites/node_vue/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marclange/Sites/node_vue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marclange/Sites/node_vue/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marclange/Sites/node_vue/plugins/**/*.{js,ts,mjs}","/Users/marclange/Sites/node_vue/composables/**/*.{js,ts,mjs}","/Users/marclange/Sites/node_vue/utils/**/*.{js,ts,mjs}","/Users/marclange/Sites/node_vue/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marclange/Sites/node_vue/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marclange/Sites/node_vue/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marclange/Sites/node_vue/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;